#
# continuous integration workflow
#
name: build repo

on:
   push:
      branches: [master]
   pull_request:
      branches: [master]
   workflow_dispatch:
      branches: [master]

jobs:
   build_ros2:
      uses: ros-misc-utilities/action-ros-ci/.github/workflows/ros2_ci.yml@master
      with:
         repo: ${{ github.event.repository.name }}
